INSERT INTO tb_states (id, state_abbreviation, name)
VALUES
    (gen_random_uuid(), 'AC', 'Acre'),
    (gen_random_uuid(), 'AL', 'Alagoas'),
    (gen_random_uuid(), 'AP', 'Amapá'),
    (gen_random_uuid(), 'AM', 'Amazonas'),
    (gen_random_uuid(), 'BA', 'Bahia'),
    (gen_random_uuid(), 'CE', 'Ceará'),
    (gen_random_uuid(), 'DF', 'Distrito Federal'),
    (gen_random_uuid(), 'ES', 'Espírito Santo'),
    (gen_random_uuid(), 'GO', 'Goiás'),
    (gen_random_uuid(), 'MA', 'Maranhão'),
    (gen_random_uuid(), 'MT', 'Mato Grosso'),
    (gen_random_uuid(), 'MS', 'Mato Grosso do Sul'),
    (gen_random_uuid(), 'MG', 'Minas Gerais'),
    (gen_random_uuid(), 'PA', 'Pará'),
    (gen_random_uuid(), 'PB', 'Paraíba'),
    (gen_random_uuid(), 'PR', 'Paraná'),
    (gen_random_uuid(), 'PE', 'Pernambuco'),
    (gen_random_uuid(), 'PI', 'Piauí'),
    (gen_random_uuid(), 'RJ', 'Rio de Janeiro'),
    (gen_random_uuid(), 'RN', 'Rio Grande do Norte'),
    (gen_random_uuid(), 'RS', 'Rio Grande do Sul'),
    (gen_random_uuid(), 'RO', 'Rondônia'),
    (gen_random_uuid(), 'RR', 'Roraima'),
    (gen_random_uuid(), 'SC', 'Santa Catarina'),
    (gen_random_uuid(), 'SP', 'São Paulo'),
    (gen_random_uuid(), 'SE', 'Sergipe'),
    (gen_random_uuid(), 'TO', 'Tocantins');